version: '3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - /Users/thruthesky/docker/emp/src:/src
      - /Users/thruthesky/docker/emp/docker/logs:/etc/nginx/logs
    ports:
      - "80:80"
      - "443:443"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - /Users/thruthesky/docker/emp/src:/src


  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=8888
    volumes:
      - mysqldata/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysqldata: {}
