https://local.itsuda50.com/index.php?route=app.version

###
https://local.itsuda50.com/index.php?route=app.settings

###
https://local.itsuda50.com/?route=user.register&reload=true&email=user3@test.com&password=12345a

###
https://local.itsuda50.com/?route=user.login&reload=true&email=user3@test.com&password=12345a

###
https://local.itsuda50.com/?route=user.profile&reload=true&sessionId=5592-52f7119495484c1d56cf8629e9664001

###
https://local.itsuda50.com/?route=category.create&id=banana&title=Banana&category&description=I-like-Banana

###

https://local.itsuda50.com/?route=category.get&reload=true&id=apple

###
https://local.itsuda50.com/?route=category.get&reload=true&idx=banana

###
https://local.itsuda50.com/?route=category.get&reload=true&idx=1

###
https://local.itsuda50.com/?route=category.update&reload=true&id=apple&title=t&description=d

###
https://local.itsuda50.com/?route=category.delete&reload=true&idx=1902

###
https://local.itsuda50.com/?route=post.update&idx=12602&sessionId=5592-52f7119495484c1d56cf8629e9664001&title=yoUp&content=thereUp&d=dragon

###
https://local.itsuda50.com/?route=post.get&true&idx=12602

###
https://itsuda50.com/?route=post.get&true&idx=22

###
https://local.itsuda50.com/?route=post.delete&true&idx=12602&sessionId=5592-52f7119495484c1d56cf8629e9664001


### 모든 게시판에서 최근 글 10 개를 가져온다.
http://localhost/?route=post.search


### 질문 게시판에서 최근 글 5 개를 가져온다.
http://localhost/?route=post.search&categoryId=qna&limit=5

### 질문 게시판에서 최근 글 중 2번 째 페이지에서 15 개를 가져온다.
http://localhost/?route=post.search&categoryId=qna&page=2&limit=15


###
https://itsuda50.com/?route=post.search&where=categoryId=<info> AND parentIdx=0&page=1&limit=20&order=idx&by=DESC


###
https://local.itsuda50.com/?route=comment.create&sessionId=5592-52f7119495484c1d56cf8629e9664001&content=A&rootIdx=11044&parentIdx=11044


###
https://local.itsuda50.com/?route=comment.update&sessionId=5592-52f7119495484c1d56cf8629e9664001&content=A-Updated&idx=12603

###
https://local.itsuda50.com/?route=comment.get&idx=12603

###
https://local.itsuda50.com/?route=comment.delete&sessionId=5592-52f7119495484c1d56cf8629e9664001&idx=12603


###
https://local.itsuda50.com/?route=user.update&sessionId=5592-52f7119495484c1d56cf8629e9664001&height=123&weight=45&blood_pressure_low=80&blood_pressure_hight=128&diabetes=Y&heart_disease=N

###
https://local.itsuda50.com/?route=health.create&sessionId=5592-52f7119495484c1d56cf8629e9664001&categoryId=scribble&title=yo&content=yoyoyo&reload=true

### point like search
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE'

### point like search. next page.
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE'&page=2&limit=3

### point like search for whom I liked. consdier the login user idx is 6.
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE' and fromUserIdx=6

### point like search for who liked me. consdier the login user idx is 6. including all fields.
https://local.itsuda50.com/?route=pointHistory.search&select=*&where=reason='POINT_LIKE' and toUserIdx=6


### point like search for who liked me. consdier the login user idx is 6. including all fields.
https://local.itsuda50.com/?route=searchKey.stats&days=3




### 사용자 검색. 결과: error_empty_name 에러
https://local.itsuda50.com/?route=user.search

### 사용자 검색. 동일한 이름, 닉네임을 가진 사용자의 기본 프로필 정보가 리턴된다. 결과: response: [ 1, 3, 5, ... ]
https://local.itsuda50.com/?route=user.search&name=관리자

### 사용자 검색.
https://local.itsuda50.com/?route=user.search&name=로컬



### 별쏘기. Expect: error_empty_post_idx
https://local.itsuda50.com/?route=point.move

### 별쏘기. Expect: error_empty_point
https://local.itsuda50.com/?route=point.move&postIdx=3942

### 별쏘기. Expect: error_point_must_be_bigger_than_0
https://local.itsuda50.com/?route=point.move&postIdx=3942&point=-5

### 별쏘기. Expect: error_not_logged_in
https://local.itsuda50.com/?route=point.move&postIdx=3942&point=4

### 별쏘기. Expect: error_lack_of_point
https://local.itsuda50.com/?route=point.move&postIdx=3942&point=123456789000&sessionId=1-1709d6e3c4f10eac83953ce6ed2ffd43

### 별쏘기. Expect: success
https://local.itsuda50.com/?route=point.move&postIdx=3942&point=1&sessionId=1-1709d6e3c4f10eac83953ce6ed2ffd43

### 별쏘기. Expect: success
https://local.itsuda50.com/?route=point.move&postIdx=3942&point=10&sessionId=1-1709d6e3c4f10eac83953ce6ed2ffd43


### Load advertisement. without domain. error
https://main.philov.com/index.php?route=advertisement.loadBanners

### Load advertisement. with domain.
https://main.philov.com/index.php?route=advertisement.loadBanners&cafeDomain=abc.com

### User stats
https://main.philov.com/index.php?route=user.stats


### Advertisement - load top banners of main.philov.com
https://main.philov.com/index.php?route=advertisement.loadBanners&cafeDomain=main.philov.com&code=top

### Advertisement - load top banners of main.sonub.com
https://main.philov.com/index.php?route=advertisement.loadBanners&cafeDomain=main.sonub.com&code=top

### Advertisement - load top banners of worng.domain.com. It's not main cafe. and the cafe does not exists.
https://main.philov.com/index.php?route=advertisement.loadBanners&cafeDomain=worng.domain.com&code=top
