https://local.itsuda50.com/index.php?route=app.version

###
https://local.itsuda50.com/index.php?route=app.settings

###
https://local.itsuda50.com/?route=user.register&reload=true&email=user3@test.com&password=12345a

###
https://local.itsuda50.com/?route=user.login&reload=true&email=user3@test.com&password=12345a

###
https://local.itsuda50.com/?route=user.profile&reload=true&sessionId=5592-52f7119495484c1d56cf8629e9664001

###
https://local.itsuda50.com/?route=category.create&id=banana&title=Banana&category&description=I-like-Banana

###

https://local.itsuda50.com/?route=category.get&reload=true&id=apple

###
https://local.itsuda50.com/?route=category.get&reload=true&idx=banana

###
https://local.itsuda50.com/?route=category.get&reload=true&idx=1

###
https://local.itsuda50.com/?route=category.update&reload=true&id=apple&title=t&description=d

###
https://local.itsuda50.com/?route=category.delete&reload=true&idx=1902

###
https://local.itsuda50.com/?route=post.update&idx=12602&sessionId=5592-52f7119495484c1d56cf8629e9664001&title=yoUp&content=thereUp&d=dragon

###
https://local.itsuda50.com/?route=post.get&true&idx=12602

###
https://itsuda50.com/?route=post.get&true&idx=22

###
https://local.itsuda50.com/?route=post.delete&true&idx=12602&sessionId=5592-52f7119495484c1d56cf8629e9664001


###
https://local.itsuda50.com/?route=post.search&where=(categoryId=<qna> or categoryId=<banana>)&page=1&limit=3&order=idx&by=ASC


###
https://local.itsuda50.com/?route=comment.create&sessionId=5592-52f7119495484c1d56cf8629e9664001&content=A&rootIdx=11044&parentIdx=11044


###
https://local.itsuda50.com/?route=comment.update&sessionId=5592-52f7119495484c1d56cf8629e9664001&content=A-Updated&idx=12603

###
https://local.itsuda50.com/?route=comment.get&idx=12603

###
https://local.itsuda50.com/?route=comment.delete&sessionId=5592-52f7119495484c1d56cf8629e9664001&idx=12603


###
https://local.itsuda50.com/?route=user.update&sessionId=5592-52f7119495484c1d56cf8629e9664001&height=123&weight=45&blood_pressure_low=80&blood_pressure_hight=128&diabetes=Y&heart_disease=N

###
https://local.itsuda50.com/?route=health.create&sessionId=5592-52f7119495484c1d56cf8629e9664001&categoryId=scribble&title=yo&content=yoyoyo&reload=true

### point like search
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE'

### point like search. next page.
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE'&page=2&limit=3

### point like search for whom I liked. consdier the login user idx is 6.
https://local.itsuda50.com/?route=pointHistory.search&select=idx,fromUserIdx,toUserIdx&where=reason='POINT_LIKE' and fromUserIdx=6

### point like search for who liked me. consdier the login user idx is 6. including all fields.
https://local.itsuda50.com/?route=pointHistory.search&select=*&where=reason='POINT_LIKE' and toUserIdx=6

